dist: bionic

language: php

php:
  - 7.3
  - 7.4

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - mysql -e 'create database urlhub_test;'
  - php artisan key:generate --env=testing

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
