language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_script:
  - mysql -e 'create database homestead;'
  - travis_retry composer self-update
  - cp .env.travis .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
