dist: bionic

language: php

php:
  - 7.3
  - 7.4

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs

before_script:
  - mysql -e 'create database urlhub_test;'
  - php artisan key:generate --env=testing
