language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - mysql -e 'CREATE DATABASE forge;'

script:
  - vendor/bin/phpunit
