name: dusk

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug

      # https://github.com/marketplace/actions/setup-php-action#cache-composer-dependencies
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer -V
          composer install --no-interaction --ignore-platform-reqs

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Create Database
        uses: mirromutth/mysql-action@v1.1
        with:
          collation server: 'utf8mb4_bin'
          mysql database: 'urlhub'
          mysql user: 'root'
          mysql password: 'root'

      - name: Prepare running Dusk
        run: |
          # Upgrade Chrome Driver
          php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
          # Start Chrome Driver
          ./vendor/laravel/dusk/bin/chromedriver-linux &
          # Run Laravel Server
          php artisan serve &

      - name: Run Dusk Tests
        env:
          APP_URL: "http://127.0.0.1:8000"
          DB_CONNECTION: mysql
          DB_DATABASE: urlhub
        run: php artisan dusk
