name: dusk

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare The Environment
        run: cp .env.example .env

      - name: Create Database
        uses: mirromutth/mysql-action@v1.1
        with:
          collation server: 'utf8mb4_bin'
          mysql database: 'urlhub'
          mysql user: 'root'
          mysql password: 'root'

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &
      - name: Run Laravel Server
        run: php artisan serve &

      - name: Run Dusk Tests
        env:
          APP_URL: "http://127.0.0.1:8000"
          DB_DATABASE: urlhub
        run: php artisan dusk
