name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test migration on ${{ matrix.connection }} (PHP ${{ matrix.php-version }})

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: urlhub
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0']
        connection: [mysql]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: redis, ${{ matrix.connection }}
          coverage: none
      - name: Check PHP
        run: |
          php -v
          php -m


      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Prepare Environment
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_HOST: localhost
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate:refresh
